apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: jellyfin
  labels:
    app: bazarr
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6767
    targetPort: 6767
    protocol: TCP
  selector:
    app: bazarr
